#!/bin/bash

echo "x"

DATA_PATH=$(realpath $1)
DATA_DIR=$(dirname $DATA_PATH)
if [ "$DATA_PATH" == "" ] ; then
	"usage: ./seurat_to_h5ad PATH-TO-RDS-FILE"
	exit 1
fi

CONTAINER="cancerbits/cb_zarr:1.0"

echo "seurat_to_h5ad: $DATA_PATH --> $DATA_PATH.zarr/"

podman run --rm \
	--name "convertainer_${USER}_zarr" \
	-e RUNROOTLESS=false \
	--volume="$DATA_DIR":"$DATA_DIR" \
	$CONTAINER \
	python3 -c "import anndata; import zarr; adata = anndata.read_h5ad('$DATA_PATH'); adata2 = anndata.AnnData(X = adata.X, obs = adata.obs, var = adata.var, obsm = adata.obsm, varm = adata.varm); adata2.write_zarr('$DATA_PATH.zarr')"
	